resources:
- allow-argocd-to-manage.yaml
- argocd-permissions.yaml
- https://github.com/redhat-appstudio/application-service/config/default?ref=a7dd01493c00e3d58501d95585e640c653113783
- .tekton/


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: quay.io/redhat-appstudio/application-service
  newName: quay.io/redhat-appstudio/application-service
  newTag: a7dd01493c00e3d58501d95585e640c653113783

configMapGenerator:
- literals:
  - GITHUB_ORG=""
  name: github-config
  behavior: replace

namespace: application-service

patches:
  - ./manager_resources_patch.yaml
